version: '3.4'

services:
  products-api:
    image: ${DOCKER_REGISTRY-}showcaseprojectproductsapi
    build:
      context: .
      dockerfile: src/Products/ShowcaseProject.Products.API/Dockerfile
    depends_on:
      - mssql-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__ProductDatabase=Server=mssql-db;Database=master;User Id=SA;Password=Password123!;TrustServerCertificate=true;
    ports:
      - 3080:80
      - 3443:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD : 'Password123!'
    ports:
      - 1433:1433
    volumes:
      - msssqldb-volume:/var/opt/mssql

volumes:
  msssqldb-volume: